version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tpms_be
    container_name: tpms_backend
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    env_file:
      - .env
    #    restart: unless-stopped
    depends_on:
      - postgres


  postgres:
    image: 'postgres:latest'
    container_name: tmps_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      PGDATA: /data/postgres
    ports:
      - "5555:5432"